import './styles/globals.css';
import { Quicksand } from 'next/font/google';
import { config } from '@fortawesome/fontawesome-svg-core';
import '@fortawesome/fontawesome-svg-core/styles.css';
import fontawesome from '@/fontawesome config/fontawesome'; // Your fontawesome.js file

config.autoAddCss = false; // Prevents CSS from being automatically added

const quicksand = Quicksand({ subsets: ['latin'] });

export const metadata = {
    title: 'Byte Flow',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={quicksand.className}>{children}</body>
        </html>
    )
}
